name: CICD for Group 2 Chat Application - Development
run-name: ${{ github.actor }} is running CICD for Group 2 Chat Application - Development

# The workflow is triggered on pull request event to the 'uat' branch
on:
  push:
    branches:
      - 'feature**'
  
# Define permissions for this workflow, which can be added at either the job or workflow level.      
permissions:
  id-token: write # This is required for requesting the JWT.
  actions: read # Permission to read actions.
  contents: read # Permission to read contents.
  security-events: write # Grants permission to write security event data for the repository.


jobs:

  # The pre-deploy job just prints the type of event and branch that triggered the workflow
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event_name }} event on ${{ github.ref_name }} branch."

  # This job is responsible for running unit tests on the application
  unit-testing:
    runs-on: ubuntu-latest
    needs: pre-deploy
    name: Unit Testing
    steps:
       # Checkout the latest code from the repository.
      - name: Checkout repo code
        uses: actions/checkout@v3
       # Install the required npm dependencies for the application
      - name: Install dependencies
        run: npm install
      # Execute unit tests using npm test
      - name: Run unit tests
        run: npm test

        